#cloud-config
# https://cloudinit.readthedocs.io/en/latest/topics/examples.html
package_update: true
packages:
  - docker.io
write_files:
  - path: /root/psql_dump.sql
    content: |
      CREATE TABLE accounts (
        user_id serial PRIMARY KEY,
        username VARCHAR ( 50 ) UNIQUE NOT NULL,
        password VARCHAR ( 50 ) NOT NULL,
        token VARCHAR ( 50 ),
        created_on TIMESTAMP NOT NULL,
          last_login TIMESTAMP 
      );

      CREATE TABLE operations (
        operation_id serial PRIMARY KEY,
        user_id INT REFERENCES accounts(user_id),
        first_value INT NOT NULL,
        second_value INT NOT NULL,
        result_value INT NOT NULL,
        created_on TIMESTAMP NOT NULL
      );
  - path: /root/Dockerfile
    content: |
      FROM postgres
      WORKDIR /docker-entrypoint-initdb.d
      ADD psql_dump.sql /docker-entrypoint-initdb.d
      EXPOSE 5432
runcmd:
  - apt update
  - apt install docker.io
  - cd /root
  - docker build -t postgres-dump .
  - docker run --name postgres-crud -p 5432:5432 -e POSTGRES_PASSWORD=fred -d postgres-dump
